# This parameter is for 50Msps and 150Mbps
#create_clock -period 6.667 -name AdcBitClk -waveform {0.000 3.333} [get_ports dco_p]
# This parameter is for 100Msps and 300Mbps
#create_clock -period 3.333 -name AdcBitClk -waveform {0.000 1.667} [get_ports dco_p]
# This parameter is for 125Msps and 375Mbps
#create_clock -period 2.667 -name AdcBitClk -waveform {0.000 1.333} [get_ports dco_p]
#create_clock -period 20.000 -name SysClk -waveform {0.000 10.000} [get_ports clk]

#set_false_path  -from [get_ports dco_p] -through [get_cells uut_dco_iserdes2] -through [get_cells uut0_BUFIO] -to [get_cells -hierarchical "*iserdes2"]
#create_generated_clock -name AdcBitClkDiv -source [get_pins uut_dco_iserdes2/DDLY] -divide_by 3 [get_nets -hierarchical "*w_fc_clk*"]
#set_false_path -from [get_clocks AdcBitClkDiv] -to [get_clocks AdcBitClk]
#set_false_path -from [get_clocks AdcBitClk] -to [get_clocks AdcBitClk]

# Application constraints
#set_false_path -from [get_clocks IntMmcm_SysClk3] -to [get_clocks AdcBitClkDiv]
#set_false_path -from [get_clocks AdcBitClkDiv] -to [get_clocks IntMmcm_SysClk3]
#set_false_path -from [get_clocks AdcBitClkDiv] -to [get_clocks IntMmcm_SysClk1]
#set_false_path -from [get_clocks IntMmcm_SysClk1] -to [get_clocks AdcBitClkDiv]

#-------------------------------------------------------------------------------------------
# Create and area for the out_of_context design block.
#-------------------------------------------------------------------------------------------
#create_pblock Apps_AdcToplevel
#resize_pblock [get_pblocks Apps_AdcToplevel] -add {SLICE_X0Y60:SLICE_X7Y89}
#    add_cells_to_pblock [get_pblocks Apps_AdcToplevel] [get_cells -quiet [list #        Apps_AdcToplevel_I_AdcToplevel
#       ]]

set_property PACKAGE_PIN M15 [get_ports rst]
set_property PACKAGE_PIN U18 [get_ports clk]

# fco assign to MRCC pin
set_property PACKAGE_PIN J18 [get_ports fco_p]
set_property PACKAGE_PIN H18 [get_ports fco_n]
# dco assign to MRCC pin
set_property PACKAGE_PIN K17 [get_ports dco_p]
set_property PACKAGE_PIN K18 [get_ports dco_n]
set_property PACKAGE_PIN L16 [get_ports adclk_p]
set_property PACKAGE_PIN L17 [get_ports adclk_n]
set_property PACKAGE_PIN G17 [get_ports din1A_p]
set_property PACKAGE_PIN G18 [get_ports din1A_n]
set_property PACKAGE_PIN H17 [get_ports din0A_n]
set_property PACKAGE_PIN H16 [get_ports din0A_p]
set_property PACKAGE_PIN G15 [get_ports din1B_n]
set_property PACKAGE_PIN H15 [get_ports din1B_p]
set_property PACKAGE_PIN H20 [get_ports din0B_n]
set_property PACKAGE_PIN J20 [get_ports din0B_p]

set_property PACKAGE_PIN U15 [get_ports uart_rx]
set_property PACKAGE_PIN U14 [get_ports uart_tx]
set_property PACKAGE_PIN N16 [get_ports spi_clk]
set_property PACKAGE_PIN N15 [get_ports spi_csb]
set_property PACKAGE_PIN L15 [get_ports spi_sdio]

set_property PACKAGE_PIN V16 [get_ports Bit_sta]
set_property PACKAGE_PIN W20 [get_ports Bit_cha]
set_property PACKAGE_PIN V17 [get_ports Bit_clr]
set_property PACKAGE_PIN N20 [get_ports Bit_clk]
set_property PACKAGE_PIN V5  [get_ports Bit_dat[0]]
set_property PACKAGE_PIN W15 [get_ports Bit_dat[1]]
set_property PACKAGE_PIN U20 [get_ports Bit_dat[2]]
set_property PACKAGE_PIN T20 [get_ports Bit_dat[3]]
set_property PACKAGE_PIN U17 [get_ports Bit_dat[4]]
set_property PACKAGE_PIN Y16 [get_ports Bit_dat[5]]
set_property PACKAGE_PIN Y17 [get_ports Bit_dat[6]]
set_property PACKAGE_PIN Y18 [get_ports Bit_dat[7]]
set_property PACKAGE_PIN Y19 [get_ports Bit_dat[8]]
set_property PACKAGE_PIN W14 [get_ports Bit_dat[9]]
set_property PACKAGE_PIN T16 [get_ports Bit_dat[10]]
set_property PACKAGE_PIN Y14 [get_ports Bit_dat[11]]
set_property PACKAGE_PIN U19 [get_ports Bit_dat[12]]
set_property PACKAGE_PIN U13 [get_ports Bit_dat[13]]
set_property PACKAGE_PIN P20 [get_ports Bit_dat[14]]
set_property PACKAGE_PIN V18 [get_ports Bit_dat[15]]

set_property PACKAGE_PIN V11 [get_ports test_pin[0]]
set_property PACKAGE_PIN V10 [get_ports test_pin[1]]
set_property PACKAGE_PIN Y8  [get_ports test_pin[2]]
set_property PACKAGE_PIN Y9  [get_ports test_pin[3]]
set_property PACKAGE_PIN W6  [get_ports test_pin[4]]
set_property PACKAGE_PIN V6  [get_ports test_pin[5]]
set_property PACKAGE_PIN V8  [get_ports test_pin[6]]
set_property PACKAGE_PIN W8  [get_ports test_pin[7]]
set_property PACKAGE_PIN Y12 [get_ports test_pin[8]]
set_property PACKAGE_PIN Y13 [get_ports test_pin[9]]

set_property IOSTANDARD LVCMOS25 [get_ports rst]
set_property IOSTANDARD LVDS_25 [get_ports din1A_p]
set_property IOSTANDARD LVDS_25 [get_ports din1A_n]
set_property IOSTANDARD LVDS_25 [get_ports din0A_p]
set_property IOSTANDARD LVDS_25 [get_ports din0A_n]
set_property IOSTANDARD LVDS_25 [get_ports din1B_p]
set_property IOSTANDARD LVDS_25 [get_ports din1B_n]
set_property IOSTANDARD LVDS_25 [get_ports din0B_p]
set_property IOSTANDARD LVDS_25 [get_ports din0B_n]
set_property IOSTANDARD LVDS_25 [get_ports adclk_p]
set_property IOSTANDARD LVDS_25 [get_ports adclk_n]
set_property IOSTANDARD LVDS_25 [get_ports fco_p]
set_property IOSTANDARD LVDS_25 [get_ports fco_n]
set_property IOSTANDARD LVDS_25 [get_ports dco_p]
set_property IOSTANDARD LVDS_25 [get_ports dco_n]

set_property IOSTANDARD LVCMOS25 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS25 [get_ports spi_csb]
set_property IOSTANDARD LVCMOS25 [get_ports spi_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]

set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_sta]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_cha]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_clr]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_clk]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[7]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[8]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[9]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[10]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[11]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[12]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[13]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[14]]
set_property IOSTANDARD LVCMOS33 [get_ports Bit_dat[15]]

set_property IOSTANDARD LVCMOS33 [get_ports test_pin[0]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[1]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[2]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[3]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[4]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[5]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[6]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[7]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[8]]
set_property IOSTANDARD LVCMOS33 [get_ports test_pin[9]]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets rst]